### ISSUE TITLE
Silently dropping packets in `tx_batch` when hardware buffer is full

### ISSUE THREAD

**Issue by 197g** [ixy-languages/ixy.rs#10]
https://github.com/ixy-languages/ixy.rs/blob/1ce633120560810a7a6dafbdf705feef77df3e32/src/ixgbe.rs#L276-L286

At this break, `packet` is dropped when the pending packet watermark is reached. I suppose it should instead be put back in front of the queue first.

**Comment by ackxolotl** [comment]
True! Well spotted :) I'm going to fix this tomorrow or on Thursday.
