### ISSUE TITLE
Undefined behavior. `conf_reg` is modified thru const reference

### ISSUE THREAD

**Issue by red75prime** [ixy-languages/ixy.rs#16]
https://github.com/ixy-languages/ixy.rs/blob/b8fbec186deba4610d1a4590e51881688c75c502/src/vfio.rs#L180-L186

**Comment by ackxolotl** [comment]
Indeed ... thanks for submitting this issue!

**Comment by ackxolotl** [comment]
Did you spot any other places with undefined behavior except the ones I fixed right now, @red75prime?

**Comment by red75prime** [comment]
@ackxolotl No, I found no more errors of this or any other type.
