### ISSUE TITLE
Ask Authorization to translate 「Writing Network Drivers in Rust - pdf」

### ISSUE THREAD

**Issue by ZhangHanDong** [ixy-languages/ixy.rs#2]
@ackxolotl 

Hi Simon Ellman,

 I like this book : [Writing Network Drivers in Rust - pdf」](https://www.net.in.tum.de/fileadmin/bibtex/publications/theses/2018-ixy-rust.pdf)，and I want to translate it to Chinese. But, I want the reader to pay one RMB(￥) for my labor, and I will add some my own content too.

do you agree? look forward to your reply.

**Comment by ackxolotl** [comment]
Hello @ZhangHanDong,

I appreciate your interest in my thesis and I think it is a great idea to translate it to Chinese! However, I prefer to keep scientific texts free to everyone and accordingly have to deny your request to sell the thesis for money.

Kind regards,
Simon Ellmann

**Comment by ZhangHanDong** [comment]
@ackxolotl 

ok，I see. thanks.
