### ISSUE TITLE
Rusty Snabb clone using Ixy

### ISSUE THREAD

**Issue by eugeneia** [ixy-languages/ixy.rs#23]
Just wanted to drop by and thank you for Ixy/Ixy.rs. I managed to pull in the latter into my embryonic Rust port of Snabb (https://twitter.com/eugeneia_/status/1248250487897337856). Worked fine, no issues. :-)

Cheers!

**Comment by ackxolotl** [comment]
Hej, great to see people using it! Guess I'll have to check out your project :-) Thanks for letting us know.
