### ISSUE TITLE
Invalid/ Missing register writes in ixgbe driver

### ISSUE THREAD

**Issue by Ramla-I** [ixy-languages/ixy.rs#29]
The following bugs are present in the ixgbe driver:

1. Write to reserved bit 31 of EIMC register in the `clear_interrupts` function
2. Write to reserved bits [15:12] of the DTXMXSZRQ register
3. Bits of RDRXCTL are not set by software. According to the datasheet:
      RDRXCTL.RSCFRSTSIZE is by default 0x8 and should be set to 0 by software.
      RDRXCTL.RSCACKC is by default 0 and should be set to 1 by software.
      RDRXCTL.FCOE_WRFIX is by default 0 and should be set to 1 by software.
4. The FCTRL register should only be modified/ updated when the RXCTRL.RXEN bit is set to 0, but the `set_promisc` function updates the filters after RXCTRL.RXEN is set.

**Comment by ackxolotl** [comment]
Thanks for reporting!
